baseurl: https://www.mrethanwebb.com
metaDataFormat: yaml
title: Ethan Webb
theme: blist-hugo-theme
DefaultContentLanguage: en
DefaultContentLanguageInSubdir: yes
languages:
  en:
    contentDir: content/en
    languageName: English
    menu:
      main:
        - name: About
          url: page/about/
          weight: 2
        - name: Projects
          url: projects
          weight: 1
    params:
      introPhoto: /ethan.jpg
      introSubtitle: 22 y/o MSc Statistics student who enjoys business, sports and using statistical analysis to make a positive change in the world.
      introTitle: Hello, I'm Ethan Webb!
    weight: 1
params:
  ascentColor: bg-blue-100
  copyright: Copyright © 2021 - Ethan Webb· All rights reserved
  darkModeToggle: yes
  enableSearch: no
  favicon: /favicon.svg
  homepage:
    social:
      description: Keep up to date by following my professional social channels.
      #dribbble: https://dribbble.com/
      github: https://github.com/
      linkedin: https://linkedin.com/in/
      #medium: https://medium.com/
      #reddit: https://reddit.com/
      title: Follow me
      #twitter: https://twitter.com/
menu:
  main:
    - name: About
      url: /about
build:
  writeStats: yes
outputs:
  home:
    - HTML
    - RSS
    - JSON
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    style: dracula
