baseurl: https://www.mrethanwebb.com
metaDataFormat: yaml
title: Ethan Webb
theme: blist-hugo-theme
DefaultContentLanguage: en
DefaultContentLanguageInSubdir: yes
languages:
  en:
    contentDir: content/en
    languageName: English
    menu:
      main:
        - name: About
          url: page/about/
          weight: 1
        - name: Projects
          url: project
          weight: 2
        - name: CV
          url: 
          weight: 3
        - name: Reading
          url: 
          weight: 4
    params:
      introPhoto: /ethan.jpg
      introSubtitle: 22 y/o MSc Statistics student who enjoys business, sports and using statistical analysis to make a positive change in the world.
      introTitle: Hello, I'm Ethan Webb!
      #button: page/about/
    weight: 1
params:
  ascentColor: bg-blue-100
  copyright: Copyright © 2021 - Varun A P· All rights reserved. Modified by Ethan Webb.
  darkModeToggle: yes
  enableSearch: no
  favicon: /favicon.svg
  homepage:
    social:
      description: Keep up to date by following my professional social channels.
      #dribbble: https://dribbble.com/
      github: https://github.com/
      linkedin: https://linkedin.com/in/
      #medium: https://medium.com/
      #reddit: https://reddit.com/
      title: Follow me
      #twitter: https://twitter.com/
menu:
  main:
    - name: About
      url: /about
build:
  writeStats: yes
outputs:
  home:
    - HTML
    - RSS
    - JSON
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    style: dracula
    
education:
  enable: true
  title: "Education"
  items:
    - university: "University of Waterloo"
      year: "2012-2017"
      degree: "Bachelor of Applied Science (BASc), Electrical Engineering"

    - university: "Sir John A Macdonald CI"
      year: "2009-2012"
      degree: "High School Diploma, Sciences, Math, Computer & Business Studies"
